---
# maintainer: opsforge
# version: 0.1

version: '2'
services:
  postgres:
    image: postgres:9.6
    hostname: postgres
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: J5brHrAXFLQSif0K
      POSTGRES_DB: netbox
    volumes:
      - ${mount_path}/netbox/db/:/var/lib/postgresql/data/
    expose:
      - 5432

  netbox:
    image: opsforge/netbox:latest
    hostname: netbox
    links:
      - postgres
    environment:
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: netbox@noreply.com
      SUPERUSER_PASSWORD: Password123
      ALLOWED_HOSTS: localhost
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: J5brHrAXFLQSif0K
      DB_HOST: postgres
      SECRET_KEY: 'r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj'
      EMAIL_SERVER: smtp.gmail.com
      EMAIL_PORT: 25
      #EMAIL_USERNAME: user
      #EMAIL_PASSWORD: password
      EMAIL_TIMEOUT: 10
      EMAIL_FROM: support@noreply.com
      NETBOX_USERNAME: guest
      NETBOX_PASSWORD: guest
    expose:
      - 8001
    volumes:
      - ${mount_path}/netbox/nginx/static:/opt/netbox/netbox/static
      - ${mount_path}/netbox/nginx/:/etc/netbox-nginx/

  nginx:
    image: nginx:1.11.1-alpine
    links:
      - netbox
    command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
    expose:
      - 80
    volumes:
      - ${mount_path}/netbox/nginx/static:/opt/netbox/netbox/static
      - ${mount_path}/netbox/nginx/:/etc/netbox-nginx/
